### ISSUE TITLE
UnsatisfiedLinkErrors in java.lang.invoke.MethodHandleNatives

### ISSUE THREAD

**Issue by gayanW** [javapathfinder/jpf-core#126]
UnsatisfiedLinkErrors when running CountDownLatchTest.

It is possible to avoid these UnsatisfiedLinkError(s) by providing dummy NativePeer methods (empty) for the missing natives in the following order.

java.lang.UnsatisfiedLinkError: cannot find native **java.lang.invoke.MethodHandleNatives.registerNatives**

    [junit] java.lang.UnsatisfiedLinkError: cannot find native java.lang.invoke.MethodHandleNatives.registerNatives
    [junit]     at java.lang.invoke.MethodHandleNatives.registerNatives(gov.nasa.jpf.vm.JPF_java_lang_invoke_MethodHandleNatives)
    [junit]     at java.lang.invoke.MethodHandleNatives.<clinit>(MethodHandleNatives.java:94)
    [junit]     at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1069)
    [junit]     at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1094)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2023)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:1516)
    [junit]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.<clinit>(AbstractQueuedSynchronizer.java:2301)
    [junit]     at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:201)
    [junit]     at gov.nasa.jpf.test.java.concurrent.CountDownLatchTest.testCountDown(CountDownLatchTest.java:43)
    [junit]     at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)

java.lang.UnsatisfiedLinkError: cannot find native **java.lang.invoke.MethodHandleNatives.getNamedCon**

    [junit] java.lang.UnsatisfiedLinkError: cannot find native java.lang.invoke.MethodHandleNatives.getNamedCon
    [junit]     at java.lang.invoke.MethodHandleNatives.getNamedCon(gov.nasa.jpf.vm.JPF_java_lang_invoke_MethodHandleNatives)
    [junit]     at java.lang.invoke.MethodHandleNatives.verifyConstants(MethodHandleNatives.java:198)
    [junit]     at java.lang.invoke.MethodHandleNatives.<clinit>(MethodHandleNatives.java:221)
    [junit]     at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1069)
    [junit]     at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1094)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2023)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:1516)
    [junit]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.<clinit>(AbstractQueuedSynchronizer.java:2301)
    [junit]     at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:201)
    [junit]     at gov.nasa.jpf.test.java.concurrent.CountDownLatchTest.testCountDown(CountDownLatchTest.java:43)
    [junit]     at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)

UnsatisfiedLinkError: cannot find native 
**java.lang.invoke.MethodHandleNatives.resolve**
```
    [junit] java.lang.Error: java.lang.IllegalAccessException: no such field: java.util.concurrent.locks.AbstractQueuedSynchronizer.state/int/getField
    [junit]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.<clinit>(AbstractQueuedSynchronizer.java:2305)
    [junit]     at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:201)
    [junit]     at gov.nasa.jpf.test.java.concurrent.CountDownLatchTest.testCountDown(CountDownLatchTest.java:43)
    [junit]     at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)
    [junit] Caused by: java.lang.IllegalAccessException: no such field: java.util.concurrent.locks.AbstractQueuedSynchronizer.state/int/getField
    [junit]     at java.lang.invoke.MemberName.makeAccessException(MemberName.java:959)
    [junit]     at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1097)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2023)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:1516)
    [junit]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.<clinit>(AbstractQueuedSynchronizer.java:2301)
    [junit]     at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:201)
    [junit]     at gov.nasa.jpf.test.java.concurrent.CountDownLatchTest.testCountDown(CountDownLatchTest.java:43)
    [junit]     at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)
    [junit] Caused by: java.lang.UnsatisfiedLinkError: cannot find native java.lang.invoke.MethodHandleNatives.resolve
    [junit]     at java.lang.invoke.MethodHandleNatives.resolve(gov.nasa.jpf.vm.JPF_java_lang_invoke_MethodHandleNatives)
    [junit]     at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1069)
    [junit]     at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1094)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2023)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:1516)
    [junit]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.<clinit>(AbstractQueuedSynchronizer.java:2301)
    [junit]     at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:201)
    [junit]     at gov.nasa.jpf.test.java.concurrent.CountDownLatchTest.testCountDown(CountDownLatchTest.java:43)
    [junit]     at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)

```

However providing empty methodsthat'll lead to,

    [junit] java.lang.NullPointerException: Calling 'getDeclaringClass()Ljava/lang/Class;' on null object
    [junit]     at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
    [junit]     at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1094)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2023)
    [junit]     at java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:1516)
    [junit]     at java.util.concurrent.locks.AbstractQueuedSynchronizer.<clinit>(AbstractQueuedSynchronizer.java:2301)
    [junit]     at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:201)
    [junit]     at gov.nasa.jpf.test.java.concurrent.CountDownLatchTest.testCountDown(CountDownLatchTest.java:43)
    [junit]     at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
    [junit]     at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)

**Comment by cyrille-artho** [comment]
Still pending even after PR #210.
