### ISSUE TITLE
Class not found: org.slf4j.LoggerFactory

### ISSUE THREAD

**Issue by NMHai** [javapathfinder/jpf-core#168]
Hello, 

When running my program using JDART, I have encountered the error. 
Exception in thread "main" ---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFListenerException: exception during executeInstruction() notification
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:800)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.jdart.JDart.run(JDart.java:207)
	at gov.nasa.jpf.jdart.JDart.start(JDart.java:131)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:108)
Caused by: gov.nasa.jpf.vm.ClassInfoException: class not found: org.slf4j.LoggerFactory
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:363)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:147)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:149)
	at gov.nasa.jpf.jvm.bytecode.INVOKESTATIC.getClassInfo(INVOKESTATIC.java:45)
	at gov.nasa.jpf.jvm.bytecode.INVOKESTATIC.getInvokedMethod(INVOKESTATIC.java:129)
	at gov.nasa.jpf.jvm.bytecode.INVOKESTATIC.getInvokedMethod(INVOKESTATIC.java:122)
	at gov.nasa.jpf.listener.Perturbator.executeInstruction(Perturbator.java:386)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	... 10 more

It seems that JPF does not support Log4j. Is it True ? (Sorry for my confirmation). 
Is there any way to work around this problem ? 

Thank you in advance.

**Comment by NMHai** [comment]
I have found the solution. 

(1) Put all the necessary libraries somewhere (e.g. $USER_HOME/.jpf-core/libs)

(2) Modify src/main/gov/nasa/jpf/jvm/JVMSystemClassLoaderInfo.java
protected void addSystemBootClassPath () {
    String v = System.getProperty("sun.boot.class.path");

    // Traverse and Insert libraries from $USER_HOME/.jpf-core/libs into v

(3) Rebuild jpf. 

Thanks.
