### ISSUE TITLE
Model checking Groovy program using JPF

### ISSUE THREAD

**Issue by rtrimana** [javapathfinder/jpf-core#191]
Hello,

I was trying to model-check a Groovy Hello World program with JPF and I was getting the following error. My Groovy source code only contains

`print "Hello World!\n"`

Here is the complete command line output from JPF:

JavaPathfinder core system v8.0 (rev ae080454541422bf296056516153e8e46474922d) - (C) 2005-2014 United States Government. All rights reserved.

====================================================== system under test
HelloWorld.main()

====================================================== search started: 6/3/19 11:01 AM
[WARNING] orphan NativePeer method: java.util.ResourceBundle.getClassContext()[Ljava/lang/Class;

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.UnsatisfiedLinkError: cannot find native java.lang.reflect.Method.getGenericParameterTypes
	at java.lang.reflect.Method.getGenericParameterTypes(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387)
	at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:116)
	at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72)
	at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56)
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1205)
	at java.beans.Introspector.getBeanInfo(Introspector.java:426)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at java.beans.Introspector.getBeanInfo(Introspector.java:260)
	at java.beans.Introspector.<init>(Introspector.java:407)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at java.beans.Introspector.getBeanInfo(Introspector.java:260)
	at java.beans.Introspector.<init>(Introspector.java:407)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:3015)
	at java.security.AccessController.doPrivileged(AccessController.java:55)
	at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3013)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:2996)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:120)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:73)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:33)
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:62)
	at java.lang.Class.initialize0(gov.nasa.jpf.vm.JPF_java_lang_Class)
	at java.lang.Class.forName(Class.java:229)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:65)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:62)
	at java.security.AccessController.doPrivileged(AccessController.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:62)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:159)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at HelloWorld.main(HelloWorld.groovy:13)

====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  owned locks:java.lang.Class@185,java.lang.Class@19e
  call stack:
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:33)
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:62)
	at java.lang.Class.initialize0(Class.java)
	at java.lang.Class.forName(Class.java:229)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:65)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:62)
	at java.security.AccessController.doPrivileged(AccessController.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:62)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:159)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at HelloWorld.main(HelloWorld.groovy:13)

====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.UnsatisfiedLinkError: cannot find native..."

====================================================== statistics
elapsed time:       00:00:01
states:             new=92,visited=0,backtracked=0,end=0
search:             maxDepth=92,constraints=0
choice generators:  thread=92 (signal=0,lock=1,sharedRef=0,threadApi=0,reschedule=91), data=0
heap:               new=30714,released=11284,maxLive=18296,gcCycles=91
instructions:       4616606
max memory:         481MB
loaded code:        classes=513,methods=10538

====================================================== search finished: 6/3/19 11:01 AM

**Comment by cyrille-artho** [comment]
It seems that the model class `java.lang.reflect.Method` exists, and method `getGenericParameterTypes` has been declared as a native method. However, the native peer class in
`src/peers/gov/nasa/jpf/vm/JPF_java_lang_reflect_Method.java` lacks this method.
You can try to implement it, based on `getParameterTypes`. However, this requires a good understanding of bytecode and the JVM.

**Comment by rtrimana** [comment]
Thank you @cyrille-artho ! I tried to implement that method (just the signature and some return value), but then I got another error message below. When I checked the java.lang.Class model implementation (in the classes directory), it has a bunch of methods with "throw new UnsupportedOperationException()" including the java.lang.Class.getTypeParameters that is complained about below. So I am getting the impression that JPF's reflection has not been fully developed at this point? And hence it needs a lot of work to model-check reflection-heavy applications? Do you have any thoughts?



JavaPathfinder core system v8.0 (rev ae080454541422bf296056516153e8e46474922d) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
HelloWorld.main()

====================================================== search started: 6/5/19 5:17 PM
[WARNING] orphan NativePeer method: java.util.ResourceBundle.getClassContext()[Ljava/lang/Class;

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.UnsupportedOperationException
        at java.lang.Class.getTypeParameters(Class.java:282)
        at com.sun.beans.TypeResolver.getActualType(TypeResolver.java:372)
        at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:96)
        at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387)
        at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:116)
        at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72)
        at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56)
...

**Comment by cyrille-artho** [comment]
Yes, the reflection capabilities in JPF were implemented on a case-by-case basis, as needed.
This means there is still more work to be done; the good news is, though, that the key mechanisms are all there. The existing code, although not necessarily simple, shows how they can be implemented. The missing functionality mostly consists of variations of the existing one, although the addition of types (generics) may complicate things somewhat.
If you know the structure of Java bytecode and its type system well, then you can probably add the missing methods in a couple of days. It is hard to tell if that will uncover more dependencies, though.

**Comment by rtrimana** [comment]
Do you think getTypeParameters() should be implemented as a method in the java.lang.Class of the model implementation? Or would it be better to be implemented as a native method there and be instantiated in JPF_java_lang_Class? 

I couldn't find any class or methods that could provide the type parameters info, so I was thinking of implementing something perhaps in the ClassInfo.java or even create a TypeParametersInfo.java. Do you have any advice?

**Comment by cyrille-artho** [comment]
In general, if it's reasonably feasible to implement a method based on existing methods from model classes or their native peers, it's preferable not to have to write a new native peer. Native peer code is much more low-level and harder to write and maintain.
In your case, the generic types may not be available through existing model class methods or native peers. That leaves you no other choice but to write your own. You can always start by extending ClassInfo and then refactoring the code into a new class, as you progress.

**Comment by d1vyanshu-kumar** [comment]
Hello @cyrille-artho, it looks like this issue hasn't been picked up yet. I'll start working on it now.

**Comment by cyrille-artho** [comment]
Yes, given that the last entry is from five years ago, it is safe to
assume that this issue did not see any action.

On Mon, Dec 2, 2024 at 1:29 PM Divyanshu Kumar ***@***.***> wrote:
>
> Hello @cyrille-artho, it looks like this issue hasn't been picked up yet. I'll start working on it now.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
Regards,
Cyrille Artho

**Comment by rtrimana** [comment]
Hi @d1vyanshu-kumar and @cyrille-artho , I actually have the working JPF version, but I did it with the JPF snapshot that worked for Java 8 (around 4-5 years ago). It is available here: https://github.com/uci-plrg/iotcheck. Apologies that I got busy with other stuff over the years and did not have a chance to merge it with the main JPF repo here. :) It has Groovy support and it can handle many types of Java reflections. My team and I tested it for hundreds of Groovy apps that are usually reflection heavy.

**Comment by cyrille-artho** [comment]
Hi,
Great to hear that you were successful with extending JPF. We would be very happy if we could integrate your code. Perhaps the current version can be integrated with branch `java-8` before we investigate how far it is compatible with Java 11?

**Comment by rtrimana** [comment]
Could @d1vyanshu-kumar help with the integration by any chance? I don't think I would have more bandwidth to do so in the near future.

**Comment by d1vyanshu-kumar** [comment]
@rtrimana Sure, I'd be happy to help with the integration.

**Comment by Harsh4902** [comment]
@cyrille-artho @rtrimana I tested a sample Groovy program on the current version of JPF, and it failed because JPF does not yet support reading JAR files. I suggest addressing this issue in the current version of JPF.

Stacktrace:
```
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchMethodException: jdk.internal.misc.SharedSecrets.setJavaUtilZipFileAccess(Ljdk/internal/misc/JavaUtilZipFileAccess;)V
	at java.util.zip.ZipFile.<clinit>(ZipFile.java:1151)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
	at java.net.URL.openStream(URL.java:1165)
	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:147)
	at org.codehaus.groovy.reflection.GeneratedMetaMethod$DgmMethodRecord.loadDgmInfo(GeneratedMetaMethod.java:179)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:205)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:112)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:90)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:82)
	at java.lang.Class.initialize0(gov.nasa.jpf.vm.JPF_java_lang_Class)
	at java.lang.Class.forName(Class.java:273)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:67)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:64)
	at java.security.AccessController.doPrivileged(AccessController.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:64)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	at helloWorld.main(helloWorld.groovy:13)
```

**Comment by rtrimana** [comment]
@Harsh4902 thanks for your message. I think at least 5 years ago, JPF supports having Java libraries in the form of JAR files. As for the Groovy program, IIRC one has to compile the code to Java bytecode and that bytecode file is the one consumed by JPF. Please CMIIW.

**Comment by Harsh4902** [comment]
@rtrimana Yes, it still supports libraries in the form of JAR file. But here, the problem is with the class or a system which we are running on JPF and which tries to access/read JAR file for some purpose.

**Comment by Rajat10xio** [comment]
> [@cyrille-artho](https://github.com/cyrille-artho) [@rtrimana](https://github.com/rtrimana) I tested a sample Groovy program on the current version of JPF, and it failed because JPF does not yet support reading JAR files. I suggest addressing this issue in the current version of JPF.
> 
> Stacktrace:
> 
> ```
> gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
> java.lang.NoSuchMethodException: jdk.internal.misc.SharedSecrets.setJavaUtilZipFileAccess(Ljdk/internal/misc/JavaUtilZipFileAccess;)V
> 	at java.util.zip.ZipFile.<clinit>(ZipFile.java:1151)
> 	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
> 	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
> 	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
> 	at java.net.URL.openStream(URL.java:1165)
> 	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:147)
> 	at org.codehaus.groovy.reflection.GeneratedMetaMethod$DgmMethodRecord.loadDgmInfo(GeneratedMetaMethod.java:179)
> 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:205)
> 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:112)
> 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:90)
> 	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
> 	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:82)
> 	at java.lang.Class.initialize0(gov.nasa.jpf.vm.JPF_java_lang_Class)
> 	at java.lang.Class.forName(Class.java:273)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:67)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:64)
> 	at java.security.AccessController.doPrivileged(AccessController.java:34)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:64)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:161)
> 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
> 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
> 	at helloWorld.main(helloWorld.groovy:13)
> ```

The issue arises because Java PathFinder (JPF) does not support reading JAR files, which is critical for Groovy since its runtime relies on dynamically loading classes and resources from JARs. This leads to errors during execution, as JPF cannot simulate Groovy's class-loading mechanism or handle internal dependencies packaged in JAR files. Consequently, JPF fails to run Groovy programs, making it unsuitable for testing Groovy applications unless JPF is enhanced to support JAR file reading.

**Comment by rtrimana** [comment]
Hey @Rajat10xio and @Harsh4902 , I think you both can try to create that feature for JPF. I certainly contributed a few code/bug fixes in the past. Currently, @d1vyanshu-kumar is trying to integrate [IoTCheck](https://github.com/uci-plrg/iotcheck), the Groovy model checker I created based on JPF. IIRC, I didn't create any JAR file reading feature. JPF is capable of running a bytecode file and it can simulate what needs to happen for a runtime library, even just print out a message instead of executing the function call. What was instrumental, I remember, was the fact that JPF did not (and maybe still does not) support reflection. Groovy programs rely a lot on Java reflection. That's the main thing I added to JPF that is wrapped around in IoTCheck. @d1vyanshu-kumar is trying to integrate just the Java Reflection feature in IoTCheck's JPF into the current main branch JPF in this repo. Hope that helps.

**Comment by rtrimana** [comment]
For example, what I did was, from the stack trace that @Rajat10xio posted above, I would try to debug JPF and see where it would fail (which part of the code). The class names are mentioned in the stack trace. Usually, I would see some JPF part that is yet to be developed/coded up. This wouldn't be the case with off-the-shelf JVM because they have all the features (includint reflection), so I would compare the classes between JPF's JVM and the off-the-shelf JVM. The source codes would not be exactly the same, but the off-the-shelf JVM would give some idea on how things should be developed.

**Comment by This-Is-Ram** [comment]
Hi, I tried to understand this issue and found that the failure happens because Groovy relies on native Java reflection methods (for example Method.getGenericParameterTypes) which are not implemented in JPF. So even a simple Groovy “Hello World” fails during Groovy runtime initialization.

Since full Groovy support seems out of scope for a first issue, I’d like to ask what would be the preferred beginner contribution here: documenting this limitation or improving the error message to make this clearer for users.
