### ISSUE TITLE
A bug in java.lang.StringBuilder.append(char c)

### ISSUE THREAD

**Issue by rtrimana** [javapathfinder/jpf-core#201]
I have just observed a different behavior in the method `append(char c)` compared to the standard java.lang.StringBuilder library for the following code:

	  StringBuilder sb = new StringBuilder(0);
	  sb.append('[');
	  sb.append(']');
	  System.out.println(sb.toString());

On standard JVM:
`[]`

On JPF:
```
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFException: illegal array offset: 0
	at gov.nasa.jpf.vm.ElementInfo.checkArray(ElementInfo.java:1180)
	at gov.nasa.jpf.vm.ElementInfo.setCharElement(ElementInfo.java:1279)
	at gov.nasa.jpf.vm.MJIEnv.setCharArrayElement(MJIEnv.java:408)
	at gov.nasa.jpf.vm.JPF_java_lang_StringBuilder.append__C__Ljava_lang_StringBuilder_2(JPF_java_lang_StringBuilder.java:154)
```

I am proposing the following fix in the native method:
```
public int append__C__Ljava_lang_StringBuilder_2 (MJIEnv env, int objref, char c) {
    int aref = env.getReferenceField(objref, "value");
    int alen = env.getArrayLength(aref);
    int count = env.getIntField(objref, "count");
    int i;
    int n = count +1;

    // TODO: Need to allocate something if the initial array is really empty
    if (alen == 0) {
      $init____V (env, objref);
      aref = env.getReferenceField(objref, "value");
      alen = env.getArrayLength(aref);
    }
    if (n < alen) {
      env.setCharArrayElement(aref, count, c);
    } else {
      int m = 3 * alen / 2;
      int arefNew = env.newCharArray(m);
      for (i = 0; i < count; i++) {
        env.setCharArrayElement(arefNew, i, env.getCharArrayElement(aref, i));
      }
      env.setCharArrayElement(arefNew, count, c);
      env.setReferenceField(objref, "value", arefNew);
    }
    
    env.setIntField(objref, "count", n);
    
    return objref;
    
  }
```
Basically `alen` needs to be checked and if it is 0, we need to allocate some array to allow appending new characters.

**Comment by cyrille-artho** [comment]
Thank you for spotting and diagnosing this. Please make a patch with the example as a unit test and the fix for the native peer.
I will be away during the next ten days, so I am not sure if there will be anyone watching the open pull requests, but we'll eventually merge it (if it passes all tests and checks the result of `sb.toString` with an assertion).
