### ISSUE TITLE
Mutual recursion caused by dependency between Package and Module classes

### ISSUE THREAD

**Issue by yuvaraj-anbarasan** [javapathfinder/jpf-core#238]
JPF is unable to resolve mutually dependent classes while parsing bootstrap methods. One such case is the dependency between Package and Module classes. In this case, the bootstrap method of the Package class is dependent on the module class method and vice versa. Hence leads to an infinite recursion caused by the dependency between these classes.
```
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFNativePeerException: exception in native method java.lang.ClassLoader.getPackages
	at gov.nasa.jpf.vm.NativeMethodInfo.executeNative(NativeMethodInfo.java:186)
	at gov.nasa.jpf.jvm.bytecode.EXECUTENATIVE.execute(EXECUTENATIVE.java:73)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1908)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.util.test.TestJPF.createAndRunJPF(TestJPF.java:675)
	at gov.nasa.jpf.util.test.TestJPF.noPropertyViolation(TestJPF.java:806)
	at gov.nasa.jpf.util.test.TestJPF.verifyNoPropertyViolation(TestJPF.java:830)
	at gov.nasa.jpf.test.java.net.URLClassLoaderTest.testGetPackages(URLClassLoaderTest.java:452)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gov.nasa.jpf.util.test.TestJPF.invoke(TestJPF.java:499)
	at gov.nasa.jpf.util.test.TestJPF.runTests(TestJPF.java:558)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gov.nasa.jpf.tool.RunTest.main(RunTest.java:185)
Caused by: java.lang.StackOverflowError
	at java.base/jdk.internal.jimage.BasicImageReader.slice(BasicImageReader.java:211)
	at java.base/jdk.internal.jimage.BasicImageReader.readBuffer(BasicImageReader.java:355)
	at java.base/jdk.internal.jimage.BasicImageReader.getResourceBuffer(BasicImageReader.java:421)
	at java.base/jdk.internal.jimage.BasicImageReader.getResource(BasicImageReader.java:392)
	at java.base/jdk.internal.jimage.ImageReader$SharedImageReader.getResource(ImageReader.java:551)
	at java.base/jdk.internal.jimage.ImageReader.getResource(ImageReader.java:109)
	at java.base/jdk.internal.jrtfs.SystemImage$1.getResource(SystemImage.java:68)
	at java.base/jdk.internal.jrtfs.JrtFileSystem.getFileContent(JrtFileSystem.java:258)
	at java.base/jdk.internal.jrtfs.JrtFileSystem.newByteChannel(JrtFileSystem.java:351)
	at java.base/jdk.internal.jrtfs.JrtPath.newByteChannel(JrtPath.java:696)
	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newByteChannel(JrtFileSystemProvider.java:302)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
	at gov.nasa.jpf.jvm.JRTClassFileContainer.getMatch(JRTClassFileContainer.java:27)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getMatch(ClassLoaderInfo.java:669)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:343)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:148)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:150)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setBootstrapMethod(JVMClassInfo.java:130)
	at gov.nasa.jpf.jvm.ClassFile.setBootstrapMethod(ClassFile.java:680)
	at gov.nasa.jpf.jvm.ClassFile.parseBootstrapMethodAttr(ClassFile.java:1516)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:108)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:657)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1397)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:966)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:742)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:61)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:36)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:354)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:148)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:150)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setBootstrapMethod(JVMClassInfo.java:130)
	at gov.nasa.jpf.jvm.ClassFile.setBootstrapMethod(ClassFile.java:680)
	at gov.nasa.jpf.jvm.ClassFile.parseBootstrapMethodAttr(ClassFile.java:1516)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:108)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:657)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1397)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:966)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:742)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:61)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:36)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:354)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:148)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:150)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setBootstrapMethod(JVMClassInfo.java:130)
	at gov.nasa.jpf.jvm.ClassFile.setBootstrapMethod(ClassFile.java:680)
	at gov.nasa.jpf.jvm.ClassFile.parseBootstrapMethodAttr(ClassFile.java:1516)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:108)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:657)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1397)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:966)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:742)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:61)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:36)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:354)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:148)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:150)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setBootstrapMethod(JVMClassInfo.java:130)
	at gov.nasa.jpf.jvm.ClassFile.setBootstrapMethod(ClassFile.java:680)
	at gov.nasa.jpf.jvm.ClassFile.parseBootstrapMethodAttr(ClassFile.java:1516)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:108)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:657)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1397)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:966)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:742)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:61)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:36)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:354)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:148)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:150)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setBootstrapMethod(JVMClassInfo.java:130)
	at gov.nasa.jpf.jvm.ClassFile.setBootstrapMethod(ClassFile.java:680)
	at gov.nasa.jpf.jvm.ClassFile.parseBootstrapMethodAttr(ClassFile.java:1516)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:108)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:657)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1397)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:966)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:742)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:61)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:36)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:354)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:148)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:150)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setBootstrapMethod(JVMClassInfo.java:130)
	at gov.nasa.jpf.jvm.ClassFile.setBootstrapMethod(ClassFile.java:680)
	at gov.nasa.jpf.jvm.ClassFile.parseBootstrapMethodAttr(ClassFile.java:1516)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:108)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:657)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1397)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:966)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:742)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:61)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:36)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:354)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:148)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:150)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setBootstrapMethod(JVMClassInfo.java:130)
	at gov.nasa.jpf.jvm.ClassFile.setBootstrapMethod(ClassFile.java:680)
	at gov.nasa.jpf.jvm.ClassFile.parseBootstrapMethodAttr(ClassFile.java:1516)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:108)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:657)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1397)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:966)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:742)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:61)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:36)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:354)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:148)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:150)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setBootstrapMethod(JVMClassInfo.java:130)
	at gov.nasa.jpf.jvm.ClassFile.setBootstrapMethod(ClassFile.java:680)
	at gov.nasa.jpf.jvm.ClassFile.parseBootstrapMethodAttr(ClassFile.java:1516)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:108)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:657)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1397)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:966)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:742)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:61)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:36)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:354)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:148)
	at gov.nasa.jpf.vm.ClassLoaderInfo.getCurrentResolvedClassInfo(ClassLoaderInfo.java:150)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setBootstrapMethod(JVMClassInfo.java:130)
	at gov.nasa.jpf.jvm.ClassFile.setBootstrapMethod(ClassFile.java:680)
	at gov.nasa.jpf.jvm.ClassFile.parseBootstrapMethodAttr(ClassFile.java:1516)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.setClassAttribute(JVMClassInfo.java:108)
	at gov.nasa.jpf.jvm.ClassFile.setClassAttribute(ClassFile.java:657)
	at gov.nasa.jpf.jvm.ClassFile.parseClassAttributes(ClassFile.java:1397)
	at gov.nasa.jpf.jvm.ClassFile.parse(ClassFile.java:966)
	at gov.nasa.jpf.jvm.JVMClassInfo$Initializer.<init>(JVMClassInfo.java:76)
	at gov.nasa.jpf.jvm.JVMClassInfo.<init>(JVMClassInfo.java:742)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:61)
	at gov.nasa.jpf.jvm.JVMClassFileContainer$JVMClassFileMatch.createClassInfo(JVMClassFileContainer.java:36)
.
.
.
.
.
```

**Comment by cyrille-artho** [comment]
Fixed by PR #241.
