### ISSUE TITLE
Missing fields in Package class

### ISSUE THREAD

**Issue by yuvaraj-anbarasan** [javapathfinder/jpf-core#239]
The java.lang.Package class has been restructured (from java version 9) to have an inner class which contains the version info fields related to a package. Since this change in the Package class, when setting a reference field for the version info fields, a NullPointerException is thrown as the fields exist in the inner class (i.e, VersionInfo) of the Package class.
```
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFNativePeerException: exception in native method java.lang.ClassLoader.getPackages
	at gov.nasa.jpf.vm.NativeMethodInfo.executeNative(NativeMethodInfo.java:186)
	at gov.nasa.jpf.jvm.bytecode.EXECUTENATIVE.execute(EXECUTENATIVE.java:73)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1908)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.util.test.TestJPF.createAndRunJPF(TestJPF.java:675)
	at gov.nasa.jpf.util.test.TestJPF.noPropertyViolation(TestJPF.java:806)
	at gov.nasa.jpf.util.test.TestJPF.verifyNoPropertyViolation(TestJPF.java:830)
	at gov.nasa.jpf.test.java.net.URLClassLoaderTest.testGetPackages(URLClassLoaderTest.java:452)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gov.nasa.jpf.util.test.TestJPF.invoke(TestJPF.java:499)
	at gov.nasa.jpf.util.test.TestJPF.runTests(TestJPF.java:558)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gov.nasa.jpf.tool.RunTest.main(RunTest.java:185)
Caused by: java.lang.NullPointerException
	at gov.nasa.jpf.vm.ElementInfo.setReferenceField(ElementInfo.java:952)
	at gov.nasa.jpf.vm.ElementInfo.setReferenceField(ElementInfo.java:829)
	at gov.nasa.jpf.vm.JPF_java_lang_ClassLoader.createPackageObject(JPF_java_lang_ClassLoader.java:261)
	at gov.nasa.jpf.vm.JPF_java_lang_ClassLoader.getPackages_____3Ljava_lang_Package_2(JPF_java_lang_ClassLoader.java:224)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gov.nasa.jpf.vm.NativeMethodInfo.executeNative(NativeMethodInfo.java:125)
```

**Comment by cyrille-artho** [comment]
Fixed by PR #241.
