### ISSUE TITLE
Interface annotation for array fields fails at runtime

### ISSUE THREAD

**Issue by yuvaraj-anbarasan** [javapathfinder/jpf-core#256]
AnnotationDefaultValueReflectionTest testDoubleArrayAttributeDefaultValue is an example of such case. The following is the exception thrown when the test case is run.

```
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFNativePeerException: exception in native method jdk.internal.misc.Unsafe.getLong
	at gov.nasa.jpf.vm.NativeMethodInfo.executeNative(NativeMethodInfo.java:186)
	at gov.nasa.jpf.jvm.bytecode.EXECUTENATIVE.execute(EXECUTENATIVE.java:73)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1908)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.util.test.TestJPF.createAndRunJPF(TestJPF.java:675)
	at gov.nasa.jpf.util.test.TestJPF.noPropertyViolation(TestJPF.java:806)
	at gov.nasa.jpf.util.test.TestJPF.verifyNoPropertyViolation(TestJPF.java:830)
	at gov.nasa.jpf.test.vm.basic.AnnotationDefaultValueReflectionTest.testDoubleArrayAttributeDefaultValue(AnnotationDefaultValueReflectionTest.java:336)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gov.nasa.jpf.util.test.TestJPF.invoke(TestJPF.java:499)
	at gov.nasa.jpf.util.test.TestJPF.runTests(TestJPF.java:558)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gov.nasa.jpf.tool.RunTest.main(RunTest.java:185)
Caused by: gov.nasa.jpf.JPFException: not a long[]
	at gov.nasa.jpf.vm.ArrayFields.getLongValue(ArrayFields.java:99)
	at gov.nasa.jpf.vm.ElementInfo.getLongElement(ElementInfo.java:1350)
	at gov.nasa.jpf.vm.JPF_jdk_internal_misc_Unsafe.getLong__Ljava_lang_Object_2J__J(JPF_jdk_internal_misc_Unsafe.java:573)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gov.nasa.jpf.vm.NativeMethodInfo.executeNative(NativeMethodInfo.java:125)
```

**Comment by cyrille-artho** [comment]
This seems to be because `f1.getDeclaredMethod` in testDoubleArrayAttributeDefaultValue probably returns the wrong type.

**Comment by yuvaraj-anbarasan** [comment]
The return type of `f1.getDeclaredMethod` is **Object**, later cast to `int[ ]`, which is correct. The issue is with `Arrays.equals`. The implementation of `Arrays.equals` was changed since java 9. It leverages vector-based techniques to access and compare the contents of two arrays. To access the contents of the array, `Unsafe.getLongUnaligned` is used. This method uses `Unsafe.getLong` to get value of the array based on the `offset` value. 
Since, the type of the array is not **long**, JPF throws an exception.

**Comment by cyrille-artho** [comment]
Hmm, it may be possible that `Arrays.equals` uses a "hack" here to compare the contents. If `double` and `long` are both 64 bit, as in Java, you can compare double elements as long without caring about the exact type, as you just need all bits to match.

We don't have a model class for `Arrays`, and if this "hack" is the only reason for a failure here, we might want to suppress this failure.

Could you please check if it is indeed the case that the code just needs a bit-wise comparison per element, and we could ignore the type mismatch here? That would allow us to avoid having to create a model class for `Arrays`.

**Comment by yuvaraj-anbarasan** [comment]
Fortunately, we may not need a model class for `Arrays`. The vectorized array comparison is done in `ArraysSupport.vectorizedMismatch`. In this method, the array contents are got by [**Unsafe.getLongUnaligned**](http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/777356696811/src/java.base/share/classes/jdk/internal/misc/Unsafe.java), where array of type **long** is returned based of the offset value (i.e, bi + offset) which is passed as parameter to the method.

I think adding native peer for Unsafe.getLongUnaligned, and having conditions based on the array type and offset value, would solve the issue.

**Comment by cyrille-artho** [comment]
This might work. Please try it, and try to find a way to make these methods a bit permissible w.r.t. the wrong types that match in size, though. 64 bit: double and long; 32 bit: float and int.
