### ISSUE TITLE
 C:\Users\Administrator\.jpf\site.properties ：The system could not find the specified path.

### ISSUE THREAD

**Issue by Xintao-C** [javapathfinder/jpf-core#278]
I used the JPF Eclipse plug-in to specify the location of A before, but now the plug-in is not maintained and there is no ". jpf "directory under the" C:\Users\Administrator "path, what should I do?

java.io.FileNotFoundException: C:\Users\Administrator\.jpf\site.properties (The system could not find the specified path.)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at edu.ucsb.cs.vlab.Z3.<clinit>(Z3.java:16)

**Comment by shadowasphodel2919** [comment]
Try adding a `\` after `C:\Users\Administrator` where you have specified the path, see if it solves the problem.

**Comment by Xintao-C** [comment]
> Try adding a `\` after `C:\Users\Administrator` where you have specified the path, see if it solves the problem.

I was not able to specify this path, 'C:\Users\Administrator\**.jpf** ' is the default path for the site.properties configuration file , but there is no '.jpF 'directory on my system,  as shown in the figure below.
![image](https://user-images.githubusercontent.com/43160698/102689334-30d80f80-4238-11eb-96e1-33477460f799.png)

**Comment by shadowasphodel2919** [comment]
Place the `site.properties` file you have created in the root directory where you have fetched the complete project and then specify that path in your plugin. I think this problem is arising because you are using Windows OS, and I do not think `.jpf` file is created in it.

**Comment by Xintao-C** [comment]
Thanks for your reply, but the plugin is not available now. I cannot specify the path through this plugin. Is there any other way to solve this problem?



 
---Original---

**Comment by shadowasphodel2919** [comment]
You can run the project using command prompt, you wouldn't need a plugin that way. Just follow the directions given https://github.com/javapathfinder/jpf-core/issues/274#issuecomment-717988013 here.
