### ISSUE TITLE
Cannot run the example in eclipse

### ISSUE THREAD

**Issue by 1saacYing** [javapathfinder/jpf-core#334]
hello Cyrille,
I wanted to run some examples in the src/examples. but an error issues every time. can u help?

[WARNING] unknown classpath element: /home/isaac/jpf/jpf-core/build/jpf-classes.jar
[WARNING] unknown classpath element: /home/isaac/jpf/jpf-symbc/build/jpf-symbc-classes.jar
[WARNING] orphan NativePeer method: java.lang.Class.initialize0()V
[WARNING] orphan NativePeer method: java.lang.Class.getByteArrayFromResourceStream(Ljava/lang/String;)[B
[WARNING] orphan NativePeer method: java.lang.Class.getResolvedName(Ljava/lang/String;)Ljava/lang/String;
[WARNING] orphan NativePeer method: java.lang.ClassLoader.getResource0(Ljava/lang/String;)Ljava/lang/String;
[WARNING] orphan NativePeer method: java.lang.ClassLoader.getResources0(Ljava/lang/String;)[Ljava/lang/String;
[WARNING] orphan NativePeer method: java.lang.ClassLoader.defineClass0(Ljava/lang/String;[BII)Ljava/lang/Class;
gov.nasa.jpf.vm.ClassInfoException: class not found: gov.nasa.jpf.BoxObjectCaches
    at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:363)
    at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:147)
    at gov.nasa.jpf.vm.VM.getStartupSystemClassInfos(VM.java:445)
    at gov.nasa.jpf.vm.VM.initializeMainThread(VM.java:564)
    at gov.nasa.jpf.vm.SingleProcessVM.initialize(SingleProcessVM.java:130)
    at gov.nasa.jpf.JPF.run(JPF.java:611)
    at gov.nasa.jpf.JPF.start(JPF.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at gov.nasa.jpf.tool.Run.call(Run.java:80)
    at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
[SEVERE] cannot load system class gov.nasa.jpf.BoxObjectCaches

**Comment by cyrille-artho** [comment]
I am not an expert with SPF, but this looks like you want to load a class that JPF does not support. In this case, it's one of JPF's internal classes, so this means you have either not build JPF correctly or misconfigured it.
Check the first two lines; the libraries with JPF's own classes are not found.
