### ISSUE TITLE
Challenges running java.util.logging.Logger.getLogger in JPF

### ISSUE THREAD

**Issue by copumpkin** [javapathfinder/jpf-core#341]
I have this super minimal reproduction:

```
public class Input {
  public static void main(String[] args) {
    System.out.println("-------- In main!");

    java.util.logging.Logger.getLogger("blah");
  }
}
```

I'm running it against the `java-10-gradle` branch (a8160543fecaee799587c955c429aa7f068a410a) and the first thing I get when calling that is:

```
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchMethodException: Calling java.lang.Thread.<init>(Ljava/lang/ThreadGroup;Ljava/lang/Runnable;Ljava/lang/String;JZ)V
	at java.util.logging.LogManager$Cleaner.<init>(LogManager.java:261)
	at java.util.logging.LogManager.<init>(LogManager.java:301)
	at java.util.logging.LogManager.<init>(LogManager.java:294)
	at java.util.logging.LogManager$1.run(LogManager.java:248)
	at java.util.logging.LogManager$1.run(LogManager.java:223)
	at java.security.AccessController.doPrivileged(AccessController.java:34)
	at java.util.logging.LogManager.<clinit>(LogManager.java:223)
	at java.util.logging.Logger.demandLogger(Logger.java:648)
	at java.util.logging.Logger.getLogger(Logger.java:717)
	at java.util.logging.Logger.getLogger(Logger.java:701)
	at Input.main(Input.java:5)
```

So I added an extra method with an (ignored) boolean to here: https://github.com/javapathfinder/jpf-core/blob/a8160543fecaee799587c955c429aa7f068a410a/src/classes/modules/java.base/java/lang/Thread.java#L118-L121

I then ran into a similar issue from `java.security.AccessController` and added another dummy overload there.

That got me past the initial issue, but now I'm stuck here:

```
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.misc.VM.initializeFromArchive
	at jdk.internal.misc.VM.initializeFromArchive(gov.nasa.jpf.vm.JPF_jdk_internal_misc_VM)
	at java.util.ImmutableCollections$SetN.<clinit>(ImmutableCollections.java:583)
	at java.util.Set.of(Set.java:502)
	at java.nio.file.spi.FileSystemProvider.<clinit>(FileSystemProvider.java:428)
	at sun.nio.fs.DefaultFileSystemProvider.<clinit>(DefaultFileSystemProvider.java:35)
	at java.nio.file.FileSystems.getDefault(FileSystems.java:185)
	at java.nio.file.Path.of(Path.java:147)
	at java.nio.file.Paths.get(Paths.java:69)
	at java.util.logging.LogManager.getConfigurationFileName(LogManager.java:1389)
	at java.util.logging.LogManager.readConfiguration(LogManager.java:1375)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:445)
	at java.util.logging.LogManager$2.run(LogManager.java:394)
	at java.security.AccessController.doPrivileged(AccessController.java:39)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:382)
	at java.util.logging.LogManager.getLogManager(LogManager.java:430)
	at java.util.logging.Logger.demandLogger(Logger.java:648)
	at java.util.logging.Logger.getLogger(Logger.java:717)
	at java.util.logging.Logger.getLogger(Logger.java:701)
	at Input.main(Input.java52)
```

Which doesn't seem to be as easy to fix as the two above. Anyone have hints for how to get past this?

**Comment by Rohan-here** [comment]
is somebody working on this? I would like to pick it up

**Comment by d1vyanshu-kumar** [comment]
Hello @cyrille-artho @copumpkin, 
it seems like no one is working on this issue. I'll start working on it now.

**Comment by cyrille-artho** [comment]
Yes, whenever there is no concrete discussion on a solution attempt for a given issue, this means that nobody is working on it.

**Comment by cyrille-artho** [comment]
The main branch of `jpf-core` is meant to run with Java 11. We still have an older version on branch `java-8`, but we don't develop that anymore. Please try using OpenJDK 11.

**Comment by adishchowdhury** [comment]
Hi @cyrille-artho can I contribute to this issue??

**Comment by shivaP192** [comment]
**Proposal: Improved Support Strategy for `java.util.logging.Logger.getLogger()` in JPF**

## Summary

While working with Java PathFinder (JPF) to verify applications that depend on `java.util.logging`, I observed that calls to `Logger.getLogger()` frequently result in class loading failures, initialization issues, or unnecessary state space expansion. This proposal outlines the technical challenges involved and suggests a structured approach to improve compatibility while preserving JPF’s verification efficiency.

---

## Problem Description

The JPF execution environment relies on model classes and native peers rather than the full host JVM implementation. The `java.util.logging` framework, however, depends on complex runtime infrastructure, including:

* Dynamic logger creation via `LogManager`
* Static initialization sequences involving configuration loading
* Handler and formatter instantiation
* ClassLoader-dependent resource resolution
* Synchronization primitives and internal caching

These mechanisms introduce several issues in JPF:

1. **Incomplete Modeling**
   The `java.util.logging` package is not fully modeled within JPF. As a result, calls to `Logger.getLogger()` may trigger `NoClassDefFoundError`, unsupported operation exceptions, or incomplete initialization sequences.

2. **Non-deterministic Initialization Behavior**
   Logger initialization may depend on environment-specific configuration, which is either absent or intentionally abstracted in JPF. This can result in inconsistent or undefined behavior during symbolic execution.

3. **State Space Explosion**
   The logging framework introduces additional objects, synchronization paths, and internal state transitions. These do not contribute to the correctness properties typically being verified but significantly increase the state space explored by JPF.

4. **Verification Irrelevance**
   Logging functionality is generally orthogonal to the logical correctness properties under verification. Executing full logging semantics adds overhead without improving verification fidelity.

---

## Proposed Solution

I propose introducing a lightweight model abstraction for `java.util.logging.Logger` that preserves interface compatibility while eliminating unnecessary execution complexity.

### Option A: Provide a Model Class Stub (Recommended)

Introduce a model class under:

```
jpf-core/src/classes/java/util/logging/Logger.java
```

Example:

```java
package java.util.logging;

public class Logger {

    protected Logger() {}

    public static Logger getLogger(String name) {
        return new Logger();
    }

    public void info(String msg) {}

    public void warning(String msg) {}

    public void severe(String msg) {}
}
```

This approach ensures:

* API compatibility
* Minimal execution overhead
* Elimination of logging-related state expansion
* Deterministic behavior during verification

---

### Option B: Conditional Execution Guard

Encourage application-level guards using:

```java
if (!gov.nasa.jpf.vm.Verify.isRunningInJPF()) {
    Logger logger = Logger.getLogger("example");
    logger.info("message");
}
```

This prevents execution of logging infrastructure when running under JPF.

---

### Option C: Native Peer Abstraction (Optional Enhancement)

If finer control is required, a native peer implementation could intercept `getLogger()` calls and return a minimal model instance, ensuring consistency across verification runs.

---

## Benefits

This proposal provides the following advantages:

* Improves compatibility with real-world Java applications
* Reduces unnecessary state space expansion
* Maintains verification performance and determinism
* Preserves API surface compatibility
* Avoids forcing application developers to modify logging code extensively

---

## Considerations

The proposed stub implementation intentionally omits:

* LogManager integration
* Handler management
* Configuration loading
* Output formatting

These behaviors are not relevant to correctness verification and would introduce unnecessary complexity.

---

## Conclusion

Providing a minimal model abstraction for `java.util.logging.Logger` aligns with JPF’s design philosophy of modeling only verification-relevant behavior. This change would improve usability for applications that rely on standard Java logging while preserving JPF’s performance and correctness guarantees.

I would be happy to contribute an initial implementation if this approach aligns with the project's direction.
