### ISSUE TITLE
Test case failure at Java-8 branch

### ISSUE THREAD

**Issue by Ao-senXiong** [javapathfinder/jpf-core#437]
This test case `testBufferConstructor` is failing during ./gradlew test under java-8 branch, is this expected?

**Comment by Ao-senXiong** [comment]
Log attached here:
```
java.lang.AssertionError: JPF found unexpected errors: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
	at gov.nasa.jpf.util.test.TestJPF.fail(TestJPF.java:164)
	at gov.nasa.jpf.util.test.TestJPF.noPropertyViolation(TestJPF.java:816)
	at gov.nasa.jpf.util.test.TestJPF.verifyNoPropertyViolation(TestJPF.java:830)
	at gov.nasa.jpf.test.java.nio.ByteBufferTest.testBufferConstructor(ByteBufferTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by cyrille-artho** [comment]
Which version of Java were you using? Note that for Java 8 and branch `java-8`, both Oracle's JDK and OpenJDK compile JPF and behave mostly similarly. I have just tried the tests, and they pass for me on Mac OS X:
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

**Comment by cyrille-artho** [comment]
Can you please try again using Oracle's JDK? That was the default we used for Java 8. For Java 11, we transitioned to OpenJDK.

**Comment by Ao-senXiong** [comment]
> Can you please try again using Oracle's JDK? That was the default we used for Java 8. For Java 11, we transitioned to OpenJDK.

Yes, I tried with Oracle's JDK and it works...

**Comment by cyrille-artho** [comment]
Thank you for confirming!
I have added a (different) phrase to `README.md` on both the `java-8` and `master` branches to clarify the Java dependencies.

**Comment by saiema** [comment]
Dear @cyrille-artho ,

I ran `./gradlew javaToolchains` and got this as the first Java SDK

```Console
> Task :javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + Oracle JDK 1.8.0_361
     | Location:           /usr/lib/jvm/jdk1.8.0_361
     | Language Version:   8
     | Vendor:             Oracle
     | Is JDK:             true
     | Detected by:        Current JVM
```

Running `java -version` returns

```Console
java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 1.8.0_361-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.361-b09, mixed mode)
```

Running `javac -version` returns

```Console
javac 1.8.0_361
```

But the weirdest thing is that it compiled, it ran, I tried to open it with IntelliJ, failed, and I deleted everything to start again. At that point I could no longer compile the project.

**Comment by saiema** [comment]
I tried again but changing  `~/.jpg/site.properties` to `~/.jpf/site.properties.bak` and now it compiles with all test passing.

My `~/.jpf/site.properties` file had the following:

```Console
jpf-core = /home/stein/Projects/Research/SPF-WCA/jpf-core
jpf-symbc = /home/stein/Projects/Research/SPF-WCA/jpf-symbc
spf-wca = /home/stein/Projects/Research/SPF-WCA/spf-wca
extensions=${jpf-core},${jpf-symbc}, ${spf-wca}
```

When renaming the `~/.jpf/site.properties.bak` file back to `~/.jpf/site.properties` the test `ByteBufferTest#testBufferConstructor` fails

```Console
gov.nasa.jpf.test.java.nio.ByteBufferTest > testBufferConstructor FAILED
    java.lang.AssertionError at ByteBufferTest.java:36
```

**Comment by cyrille-artho** [comment]
Regarding SPF, perhaps others on our Discord channel can help: https://discord.com/channels/1201877105722540043/1348691277557928027
